// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OshawaMechanic.Models;

namespace OshawaMechanic.Migrations
{
    [DbContext(typeof(OshawaMechanicContext))]
    [Migration("20201208003406_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OshawaMechanic.Models.Assignments", b =>
                {
                    b.Property<int>("assignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CoustmerscoustmerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeesemployeeId")
                        .HasColumnType("int");

                    b.Property<int>("coustmerId")
                        .HasColumnType("int");

                    b.Property<string>("employeeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("assignmentId");

                    b.HasIndex("CoustmerscoustmerId");

                    b.HasIndex("EmployeesemployeeId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OshawaMechanic.Models.Coustmers", b =>
                {
                    b.Property<int>("coustmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("coustmerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coustmerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("coustmerphoneNumber")
                        .HasColumnType("int");

                    b.HasKey("coustmerId");

                    b.ToTable("Coustmers");
                });

            modelBuilder.Entity("OshawaMechanic.Models.Employees", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("employeeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OshawaMechanic.Models.Assignments", b =>
                {
                    b.HasOne("OshawaMechanic.Models.Coustmers", "Coustmers")
                        .WithMany("Assignments")
                        .HasForeignKey("CoustmerscoustmerId");

                    b.HasOne("OshawaMechanic.Models.Employees", "Employees")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeesemployeeId");

                    b.Navigation("Coustmers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OshawaMechanic.Models.Coustmers", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("OshawaMechanic.Models.Employees", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
